name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:
  Matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

    outputs:
      releasable: ${{ steps.releasable.outputs.releasable }}

  Debug:
    needs:
      - Matrix
    runs-on: ubuntu-latest
    steps:
      - run: "echo releasable = ${{ needs.Matrix.outputs.releasable }} "

  Release:
    needs:
      - Matrix
    runs-on: ubuntu-latest
    steps:
      - name: Is releasable branch
        id: releasable
        run: |
          if [ "${{ github.event.ref }}" == 'refs/heads/master' ] \
            || [ "${{ github.event.ref }}" == 'refs/heads/main' ] \
            || [[ "${{ github.event.ref }}" =~ ^refs/heads/[0-9]+\.[0-9]+\.x$ ]] \
            || [[ "${{ github.event.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+.[0-9]+$ ]]
          then
            echo "releasable=true" 
            echo "releasable=true" >> $GITHUB_OUTPUT
          else
            echo "releasable=false" 
            echo "releasable=false" >> $GITHUB_OUTPUT
          fi          

      - name: push release
        if: ${{ steps.releasable.releasable }}
        uses: evanchooly/workflows/.github/workflows/jreleaser.yml@master
        with:
          GH_PUSH_TOKEN       : ${{ secrets.DUMMY }}
          GPG_PASSPHRASE      : ${{ secrets.DUMMY }}
          GPG_PUBLIC_KEY      : ${{ secrets.DUMMY }}
          GPG_PRIVATE_KEY     : ${{ secrets.DUMMY }}
          SONATYPE_USERNAME   : ${{ secrets.DUMMY }}
          SONATYPE_PASSWORD   : ${{ secrets.DUMMY }}