name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:
  Matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: central
          cache: maven

      - name: Find MongoDB versions
        id: mongo-versions
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          echo "mongo_versions=$( ~/.jbang/bin/jbang --verbose .github/BuildMatrix.java )" >> $GITHUB_OUTPUT

      - name: Is releasable branch
        id: releasable
        run: |
          if [ "${{ github.event.ref }}" == 'refs/heads/master' ] \
            || [ "${{ github.event.ref }}" == 'refs/heads/main' ] \
            || [[ "${{ github.event.ref }}" =~ ^refs/heads/[0-9]+\.[0-9]+\.x$ ]] \
            || [[ "${{ github.event.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+.[0-9]+$ ]]
          then
            echo "releasable=true" 
            echo "releasable=true" >> $GITHUB_OUTPUT
          else
            echo "releasable=false"
            echo "releasable=false" >> $GITHUB_OUTPUT
          fi          

    outputs:
      version_matrix: ${{ steps.mongo-versions.outputs.mongo_versions }}
      releasable: ${{ steps.releasable.outputs.releasable }}

  Release:
    needs:
      - Matrix
    if: ${{ needs.Matrix.outputs.releasable }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm releasing"
